_target_: src.models.module.LitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.01
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.simple_net.MyLSTM2
  input_size: 1024
  num_classes: 2 # [0, 1]
  dropout: 0.2
  num_layers: 1

# compile model for faster training with pytorch 2.0
compile: true